POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "jayantd",
  "password": "1234"
}
   //after generating
###

GET http://127.0.0.1:8000/articles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzMyNjQ4LCJpYXQiOjE3MzYwMDQ2NDgsImp0aSI6Ijg4NTIwMmEzODI5MTQ2OGQ5OTQ5NzFjNTg4ODY5YzYxIiwidXNlcl9pZCI6Mn0.1w-0T-Hnef3syuEDMYFTUNLuo5cFAY7XapKsyKvnwVc