# # services:
# #   - type: web
# #     name: django-backend
# #     env: python
# #     plan: free
# #     buildCommand: pip install -r requirements.txt
# #     startCommand: gunicorn news_aggregator.wsgi
# #     rootDir: news_aggregator
# #     envVars:
# #       - key: DJANGO_SECRET_KEY
# #         value: django-insecure-9qyer=*&6mkl@jla0-(43j=9_n9y41=9-lmf#o3k)tap*^5dgc
# #       - key: DEBUG
# #         value: False

# #   - type: web
# #     name: react-frontend
# #     env: static
# #     rootDir: NewsApp
# #     buildCommand: npm install && cd NewsAggregator && npm run build
# #     staticPublishPath: build


# services:
#   - type: web
#     name: django-backend
#     env: python
#     plan: free
#     buildCommand: pip install -r requirements.txt
#     startCommand: gunicorn news_aggregator.wsgi
#     rootDir: NewsAggrgator
#     envVars:
#       - key: DJANGO_SECRET_KEY
#         value: django-insecure-9qyer=*&6mkl@jla0-(43j=9_n9y41=9-lmf#o3k)tap*^5dgc
#       - key: DEBUG
#         value: False

#   - type: static
#     name: react-frontend
#     rootDir: NewsApp
#     buildCommand: npm install && cd NewsAggregator && npm run build
#     staticPublishPath: build




services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn news_aggregator.wsgi
    rootDir: NewsAggrgator
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-9qyer=*&6mkl@jla0-(43j=9_n9y41=9-lmf#o3k)tap*^5dgc
      - key: DEBUG
        value: False

  - type: web
    name: react-frontend
    env: static
    rootDir: NewsApp
    buildCommand: npm install && cd NewsAggregator && npm run build
    staticPublishPath: NewsAggregator/build
