
services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: cd news_aggregator && pip install -r requirements.txt && cd ..
    # startCommand: gunicorn news_aggregator.
    startCommand: gunicorn news_aggregator.wsgi:application
    rootDir: news_aggregator
    # rootDir: NewsAggrgator
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-9qyer=*&6mkl@jla0-(43j=9_n9y41=9-lmf#o3k)tap*^5dgc
      - key: DEBUG
        value: False

  - type: web
    name: react-frontend
    env: static
    rootDir: NewsApp
    buildCommand: cd NewsAggregator && npm install && npm run build
    staticPublishPath: NewsAggregator/build
