# Generated by Django 5.1.4 on 2025-01-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category_article_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publisher_logo',
        ),
    ]
