# Generated by Django 5.1.4 on 2025-01-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_publisher_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publisher_name',
        ),
        migrations.AddField(
            model_name='article',
            name='publisher_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
