# Generated by Django 5.1.4 on 2025-01-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_publisher_name_article_publisher_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], default='general', max_length=100),
        ),
    ]
