# Generated by Django 5.1.4 on 2025-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_category_savedarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('technology', 'Technology'), ('politics', 'Politics')], default='home', max_length=100),
        ),
    ]
